name: example CI
on:
  push:
  pull_request:
    branches:
      - "main"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .git/config
      - run: |
          echo "test 1"
          echo "Test 1"
